services:
  - type: web
    name: sistema-salones
    env: php
    plan: free
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_NAME
        value: "Sistema de Asignaci√≥n de Salones"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: sistema-salones
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: postgres
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: postgres
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres
          property: password

databases:
  - name: postgres
    plan: free
    ipAllowList: []
